[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.13.0",
    "fake-useragent>=2.2.0",
    "flask>=3.1.2",
]
